//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBase
    {
        public short ID { get; set; }
        public string DBName { get; set; }
        public string ServerName { get; set; }
    }
}
