//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAdminEntities : DbContext
    {
        public DBAdminEntities()
            : base(Shared.SharedLib.GetRDSConnectionString())
        {
        }

       

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataBase> DataBases { get; set; }
        public virtual DbSet<DataBaseType> DataBaseTypes { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
    }
}
